### ISSUE TITLE
Program Crashes/Closes

### ISSUE THREAD

**Issue by SamejimaMamimi** [ACEmulator/ACViewer#17]
I can load up dats, but almost as soon as I start navigating files the program crashes/closes.  Below is the error message. Any help appreciated, thanks!

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ACViewer.Render.TextureCache.LoadTexture(Surface surface, UInt32 textureID, Boolean useDummy, Dictionary`2 customPaletteColors) in C:\projects\acviewer\ACViewer\Render\TextureCache.cs:line 156
   at ACViewer.Render.TextureCache.GetTexture(Surface surface, UInt32 textureID, Dictionary`2 customPaletteColors, Boolean useCache) in C:\projects\acviewer\ACViewer\Render\TextureCache.cs:line 598
   at ACViewer.Render.TextureCache.Get(UInt32 fileID, List`1 textureMapChanges, Dictionary`2 customPaletteColors, Boolean useCache) in C:\projects\acviewer\ACViewer\Render\TextureCache.cs:line 549
   at ACViewer.Model.GfxObj.LoadTextures() in C:\projects\acviewer\ACViewer\Model\GfxObj.cs:line 78
   at ACViewer.Model.GfxObj..ctor(UInt32 gfxObjID, Boolean doBuild) in C:\projects\acviewer\ACViewer\Model\GfxObj.cs:line 46
   at ACViewer.Model.GfxObjCache.Get(UInt32 gfxObjID) in C:\projects\acviewer\ACViewer\Model\GfxObjCache.cs:line 25
   at ACViewer.Model.Setup..ctor(UInt32 setupID) in C:\projects\acviewer\ACViewer\Model\Setup.cs:line 37
   at ACViewer.Model.SetupCache.Get(UInt32 setupID) in C:\projects\acviewer\ACViewer\Model\SetupCache.cs:line 23
   at ACViewer.Model.SetupInstance..ctor(UInt32 setupID) in C:\projects\acviewer\ACViewer\Model\SetupInstance.cs:line 33
   at ACViewer.ModelViewer.LoadModel(UInt32 id) in C:\projects\acviewer\ACViewer\ModelViewer.cs:line 58
   at ACViewer.View.FileExplorer.ReadPortalFile(UInt32 fileID) in C:\projects\acviewer\ACViewer\View\FileExplorer.xaml.cs:line 240
   at ACViewer.View.FileExplorer.Files_SelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\projects\acviewer\ACViewer\View\FileExplorer.xaml.cs:line 186
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SetSelectedHelper(Object item, FrameworkElement UI, Boolean selected)
   at System.Windows.Controls.Primitives.Selector.NotifyIsSelectedChanged(FrameworkElement container, Boolean selected, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.ListBoxItem.OnSelected(RoutedEventArgs e)
   at System.Windows.Controls.ListBoxItem.OnIsSelectedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.ListBox.NotifyListItemClicked(ListBoxItem item, MouseButton mouseButton)
   at System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(MouseButton mouseButton)
   at System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ACViewer.View.App.Main()

**Comment by gmriggs** [comment]
You are missing the dat files.

Make sure you have all 4 of the DAT files in your folder (cell, portal, hires, language)

**Comment by SamejimaMamimi** [comment]
That was the issue, thanks! I was opening dats in my AC server folder which didn't have the hires dat. Appreciate the help, and for working on such a great utility.
